# Generated by Django 2.2.6 on 2019-10-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateNumberImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='images/')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
